declare module "vue-youtube"
declare module "vue-carousel"
declare module "vue-image-lightbox"
declare module "vue-progressive-image"
declare module "@hyjiacan/vue-ellipsis"
declare module "vue-ua"
